name: trayscale
base: core24
version: git
summary: Trayscale - GUI for Tailscale Client
description: |
  Trayscale is a system tray utility for Tailscale Client.
  It provides a convenient graphical interface to manage and monitor your Tailscale connections.
  This snap connects to an existing Tailscale client installation.
grade: stable
confinement: strict

plugs:
  tailscale-socket:
    interface: system-files
    read:
      - /var/run/tailscale/tailscaled.sock
      - /run/tailscale/tailscaled.sock
    write:
      - /var/run/tailscale/tailscaled.sock
      - /run/tailscale/tailscaled.sock

slots:
  trayscale-dbus:
    interface: dbus
    bus: session
    name: dev.deedles.Trayscale

  indicator-dbus:
    interface: dbus
    bus: session
    name: com.canonical.dbusmenu

apps:
  trayscale:
    command: bin/trayscale
    extensions: [gnome]
    desktop: meta/gui/trayscale.desktop
    plugs:
      - network
      - desktop
      - desktop-legacy
      - tailscale-socket
    slots:
      - trayscale-dbus
      - indicator-dbus

parts:
  trayscale:
    plugin: go
    source: .
    build-snaps:
      - go/latest/stable
    stage-packages:
      - libproxy1v5

  desktop-files:
    plugin: dump
    source: .
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      cp snap/trayscale.desktop $CRAFT_PART_INSTALL/meta/gui/trayscale.desktop
      cp snap/trayscale.png $CRAFT_PART_INSTALL/meta/gui/trayscale.png
